config/routes.rb
Rails.application.routes.draw do
  filter :locale

  root 'main#index'

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login', to: 'user_sessions#new', as: :login

    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback'
    get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  end

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout', to: 'user_sessions#destroy', as: :logout

    resources :cards

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card', to: 'trainer#review_card', as: :review_card
    get 'trainer', to: 'trainer#index', as: :trainer

    resources :profile, only: [:edit, :update]
  end
end

app/models/card.rb
require 'super_memo'

class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :block
  validates :user_id, presence: true
  before_validation :set_review_date_as_now, on: :create
  validate :texts_are_not_equal
  validates :original_text, :translated_text, :review_date,
            presence: { message: I18n.t('activerecord.errors.messages.blank') }
  validates :user_id,
            presence: { message: I18n.t('activerecord.errors.models.card.attributes.user.required') }
  validates :block_id,
            presence: { message: I18n.t('activerecord.errors.models.card.attributes.block.required') }
  validates :interval, :repeat, :efactor, :quality, :attempt, presence: true

  mount_uploader :image, CardImageUploader

  scope :pending, -> { where('review_date <= ?', Time.now).order('RANDOM()') }
  scope :repeating, -> { where('quality < ?', 4).order('RANDOM()') }

  def check_translation(user_translation)
    distance = Levenshtein.distance(full_downcase(translated_text),
                                    full_downcase(user_translation))

    sm_hash = SuperMemo.algorithm(interval, repeat, efactor, attempt, distance, 1)

    if distance <= 1
      sm_hash.merge!({ review_date: Time.now + interval.to_i.days, attempt: 1 })
      update(sm_hash)
      { state: true, distance: distance }
    else
      sm_hash.merge!({ attempt: [attempt + 1, 5].min })
      update(sm_hash)
      { state: false, distance: distance }
    end
  end

  def self.pending_cards_notification
    users = User.where.not(email: nil)
    users.each do |user|
      if user.cards.pending.any?
        CardsMailer.pending_cards_notification(user.email).deliver
      end
    end
  end

  protected

  def set_review_date_as_now
    self.review_date = Time.now
  end

  def texts_are_not_equal
    if full_downcase(original_text) == full_downcase(translated_text)
      errors.add(:original_text, 'Вводимые значения должны отличаться.')
    end
  end

  def full_downcase(str)
    str.mb_chars.downcase.to_s.squeeze(' ').lstrip
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = 'Вы обратились к несуществующей записи.'
    redirect_to root_path
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:destroy, :edit, :update, :set_as_current,
                                   :reset_as_current]

  def index
    @blocks = current_user.blocks.all.order('title')
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def destroy
    @block.destroy
    respond_with @block
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    respond_with @card
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id)
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::BaseController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path,
                  notice: 'Профиль пользователя успешно обновлен.'
    else
      respond_with current_user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :locale)
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController

  def index
    if params[:id]
      @card = current_user.cards.find(params[:id])
    else
      if current_user.current_block
        @card = current_user.current_block.cards.pending.first
        @card ||= current_user.current_block.cards.repeating.first
      else
        @card = current_user.cards.pending.first
        @card ||= current_user.cards.repeating.first
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def review_card
    @card = current_user.cards.find(params[:card_id])

    check_result = @card.check_translation(trainer_params[:user_translation])

    if check_result[:state]
      if check_result[:distance] == 0
        flash[:notice] = t(:correct_translation_notice)
      else
        flash[:alert] = t 'translation_from_misprint_alert',
                          user_translation: trainer_params[:user_translation],
                          original_text: @card.original_text,
                          translated_text: @card.translated_text
      end
      redirect_to trainer_path
    else
      flash[:alert] = t(:incorrect_translation_alert)
      redirect_to trainer_path(id: @card.id)
    end
  end

  private

  def trainer_params
    params.permit(:user_translation)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: 'Пользователь успешно удален.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for card do |f| %>
  <div class="form-group">
    <%= f.input :original_text,  as: :text, label: 'Оригинал',
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <div class="form-group">
    <%= f.input :translated_text,  as: :text, label: 'Перевод',
                input_html: { class: 'form-control', required: true } %>
  </div>

  <div class="form-group">
    <%= f.input :image, as: :file, label: 'Изображение' %>
    <%= f.input :image_cache, as: :hidden %>
  </div>

  <div class="form-group">
    <%= f.input :block_id, collection: current_user.blocks.all.order('title'),
                      prompt: 'Выберите колоду', label: 'Колоды',
                      input_html: { class: 'form-control', required: true } %>
  </div>

  <% if card.image? %>
    <div class="form-group">
      <%= f.input :remove_image, as: :boolean, label: 'Удалить изображение' %>
      <div class="row">
        <div class="col-xs-6 col-md-4 card_image">
          <p class="thumbnail">
            <%= image_tag card.image_url %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-default' %>
<% end %>

app/views/dashboard/cards/edit.html.erb
<h2>Редактировать карточку</h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/index.html.erb
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Оригинал</th>
    <th>Перевод</th>
    <th>Пересмотр</th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @cards.each do |card| %>
    <tr class="table table-hover table-condensed">
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
      <td><%= link_to 'Редактировать', edit_card_path(card) %></td>
      <td><%= link_to 'Удалить', card, method: :delete,
                      data: { confirm: 'Удалить запись?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/dashboard/cards/new.html.erb
<h2>Добавить карточку</h2>

<%= render 'form', card: @card %>